version: '3.8'

services:
  frontend:
    image: monodara/peacoplaza-fe:latest 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_API=http://localhost:4000/

  backend:
    build:
      context: .
    environment:
      - ConnectionStrings__Local=Host=postgres_container;Database=mydb;Username=postgres;Password=mysecretpassword
      - Jwt__Key=873463ibfjhf76dstfjhbksjd
    ports:
      - "4000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
