### Login as Admin UserRole
POST http://localhost:5074/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "john@example.com",
    "password": "admin@123"
}


### Get All Users
GET http://localhost:5074/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer 


###  create user 
POST http://localhost:5074/api/v1/users HTTP/1.1
content-type: application/json

{
    "UserName": "demo2",
    "Email": "demo2@example.com",
    "Password": "123456",
    "Role": "customer" 
}

###  update user
PUT http://localhost:5074/api/v1/users/{a675a7b0-2c30-48a0-803e-dc4be8e2229d} HTTP/1.1
content-type: application/json
Authorization: Bearer 

{
    "Name": "shami4",
    "Email": "shami@example.com",
    "Password": "1234567"
}

### delete user
Delete http://localhost:5074/api/v1/users/{15738d78-7c9c-4b5a-8c7d-42668770d1ce} HTTP/1.1
content-type: application/json
Authorization: Bearer 



### Get User by id
GET http://localhost:5074/api/v1/users/{ae575e77-9a95-4a81-b07c-5526b7dae195}
Content-Type: application/json
Authorization: Bearer  